### ISSUE TITLE
Возникла ошибка, не могу разобраться, стоковый бот с ключом доступа группы...

### ISSUE THREAD

**Issue by starcevpro** [ekonda/kubot#1]
`AttributeError: 'VKEnvironment' object has no attribute 'parent_environment'
2019-02-04 22:29:13,783 [ ERROR ] "AttributeError::'VKEnvironment' object has no attribute 'parent_environment'" on update {'type': 'message_new', 'object': {'date': 1549308553, 'from_id': 135416952, 'id': 0, 'out': 0, 'peer_id': 2000000001, 'text': 'Фир, помощь', 'conversation_message_id': 139858, 'fwd_messages': [], 'important': False, 'random_id': 0, 'attachments': [], 'is_hidden': False}, 'group_id': 177672633} from vkontakte
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/kutana/executor.py", line 116, in process
    if await callback(update, env) == "DONE":
  File "/usr/local/lib/python3.7/site-packages/kutana/plugin.py", line 88, in wrapper_for_early
    update, env, early=True
  File "/usr/local/lib/python3.7/site-packages/kutana/plugin.py", line 147, in _proc_update
    res = await callback(message, inner_env)
  File "/usr/local/lib/python3.7/site-packages/kutana/plugin.py", line 308, in wrapper
    if is_done(await coro(msg, env, **kwargs)):
  File "plugins/prefix.py", line 39, in on_has_text
    env.parent_environment.set_message(
AttributeError: 'VKEnvironment' object has no attribute 'parent_environment'
`

**Comment by michaelkrukov** [comment]
Версия Kutana, для которой написал kubot обновилась, и `parent_environment` теперь называется `parent`. Скоро обновим kubot. Спасибо.
